/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutTechnicianImport } from './routes/_layout.technician'
import { Route as LayoutSalesImport } from './routes/_layout.sales'
import { Route as LayoutInventoryImport } from './routes/_layout.inventory'
import { Route as LayoutDashboardImport } from './routes/_layout.dashboard'
import { Route as LayoutBusinessImport } from './routes/_layout.business'
import { Route as LayoutAdminImport } from './routes/_layout.admin'
import { Route as LayoutTechnicianRequestImport } from './routes/_layout.technician_.request'
import { Route as LayoutTechnicianJobImport } from './routes/_layout.technician_.job'
import { Route as LayoutTechnicianItemImport } from './routes/_layout.technician_.item'
import { Route as LayoutSalesSupplierImport } from './routes/_layout.sales_.supplier'
import { Route as LayoutSalesJobImport } from './routes/_layout.sales_.job'
import { Route as LayoutSalesCustomerImport } from './routes/_layout.sales_.customer'
import { Route as LayoutSalesActivityImport } from './routes/_layout.sales_.activity'
import { Route as LayoutInventoryRequestImport } from './routes/_layout.inventory_.request'
import { Route as LayoutInventoryLogImport } from './routes/_layout.inventory_.log'
import { Route as LayoutInventoryItemImport } from './routes/_layout.inventory_.item'
import { Route as LayoutBusinessScheduleImport } from './routes/_layout.business_.schedule'
import { Route as LayoutBusinessJobImport } from './routes/_layout.business_.job'
import { Route as LayoutAdminUserImport } from './routes/_layout.admin_.user'
import { Route as LayoutAdminRoleImport } from './routes/_layout.admin_.role'
import { Route as LayoutSalesJobCreateImport } from './routes/_layout.sales_.job_.create'
import { Route as LayoutSalesJobJobidImport } from './routes/_layout.sales_.job_.$job_id'
import { Route as LayoutSalesCustomerCreateImport } from './routes/_layout.sales_.customer_.create'
import { Route as LayoutSalesCustomerCustomeridImport } from './routes/_layout.sales_.customer_.$customer_id'
import { Route as LayoutSalesJobEditJobidImport } from './routes/_layout.sales_.job_.edit.$job_id'
import { Route as LayoutSalesCustomerEditCustomeridImport } from './routes/_layout.sales_.customer_.edit.$customer_id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutTechnicianRoute = LayoutTechnicianImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesRoute = LayoutSalesImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInventoryRoute = LayoutInventoryImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBusinessRoute = LayoutBusinessImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTechnicianRequestRoute = LayoutTechnicianRequestImport.update({
  id: '/technician_/request',
  path: '/technician/request',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTechnicianJobRoute = LayoutTechnicianJobImport.update({
  id: '/technician_/job',
  path: '/technician/job',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTechnicianItemRoute = LayoutTechnicianItemImport.update({
  id: '/technician_/item',
  path: '/technician/item',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesSupplierRoute = LayoutSalesSupplierImport.update({
  id: '/sales_/supplier',
  path: '/sales/supplier',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesJobRoute = LayoutSalesJobImport.update({
  id: '/sales_/job',
  path: '/sales/job',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesCustomerRoute = LayoutSalesCustomerImport.update({
  id: '/sales_/customer',
  path: '/sales/customer',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesActivityRoute = LayoutSalesActivityImport.update({
  id: '/sales_/activity',
  path: '/sales/activity',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInventoryRequestRoute = LayoutInventoryRequestImport.update({
  id: '/inventory_/request',
  path: '/inventory/request',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInventoryLogRoute = LayoutInventoryLogImport.update({
  id: '/inventory_/log',
  path: '/inventory/log',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInventoryItemRoute = LayoutInventoryItemImport.update({
  id: '/inventory_/item',
  path: '/inventory/item',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBusinessScheduleRoute = LayoutBusinessScheduleImport.update({
  id: '/business_/schedule',
  path: '/business/schedule',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBusinessJobRoute = LayoutBusinessJobImport.update({
  id: '/business_/job',
  path: '/business/job',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminUserRoute = LayoutAdminUserImport.update({
  id: '/admin_/user',
  path: '/admin/user',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoleRoute = LayoutAdminRoleImport.update({
  id: '/admin_/role',
  path: '/admin/role',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesJobCreateRoute = LayoutSalesJobCreateImport.update({
  id: '/sales_/job_/create',
  path: '/sales/job/create',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesJobJobidRoute = LayoutSalesJobJobidImport.update({
  id: '/sales_/job_/$job_id',
  path: '/sales/job/$job_id',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesCustomerCreateRoute = LayoutSalesCustomerCreateImport.update({
  id: '/sales_/customer_/create',
  path: '/sales/customer/create',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesCustomerCustomeridRoute =
  LayoutSalesCustomerCustomeridImport.update({
    id: '/sales_/customer_/$customer_id',
    path: '/sales/customer/$customer_id',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutSalesJobEditJobidRoute = LayoutSalesJobEditJobidImport.update({
  id: '/sales_/job_/edit/$job_id',
  path: '/sales/job/edit/$job_id',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesCustomerEditCustomeridRoute =
  LayoutSalesCustomerEditCustomeridImport.update({
    id: '/sales_/customer_/edit/$customer_id',
    path: '/sales/customer/edit/$customer_id',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/business': {
      id: '/_layout/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof LayoutBusinessImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/inventory': {
      id: '/_layout/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof LayoutInventoryImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales': {
      id: '/_layout/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof LayoutSalesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/technician': {
      id: '/_layout/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof LayoutTechnicianImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin_/role': {
      id: '/_layout/admin_/role'
      path: '/admin/role'
      fullPath: '/admin/role'
      preLoaderRoute: typeof LayoutAdminRoleImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin_/user': {
      id: '/_layout/admin_/user'
      path: '/admin/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof LayoutAdminUserImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/business_/job': {
      id: '/_layout/business_/job'
      path: '/business/job'
      fullPath: '/business/job'
      preLoaderRoute: typeof LayoutBusinessJobImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/business_/schedule': {
      id: '/_layout/business_/schedule'
      path: '/business/schedule'
      fullPath: '/business/schedule'
      preLoaderRoute: typeof LayoutBusinessScheduleImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/inventory_/item': {
      id: '/_layout/inventory_/item'
      path: '/inventory/item'
      fullPath: '/inventory/item'
      preLoaderRoute: typeof LayoutInventoryItemImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/inventory_/log': {
      id: '/_layout/inventory_/log'
      path: '/inventory/log'
      fullPath: '/inventory/log'
      preLoaderRoute: typeof LayoutInventoryLogImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/inventory_/request': {
      id: '/_layout/inventory_/request'
      path: '/inventory/request'
      fullPath: '/inventory/request'
      preLoaderRoute: typeof LayoutInventoryRequestImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales_/activity': {
      id: '/_layout/sales_/activity'
      path: '/sales/activity'
      fullPath: '/sales/activity'
      preLoaderRoute: typeof LayoutSalesActivityImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales_/customer': {
      id: '/_layout/sales_/customer'
      path: '/sales/customer'
      fullPath: '/sales/customer'
      preLoaderRoute: typeof LayoutSalesCustomerImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales_/job': {
      id: '/_layout/sales_/job'
      path: '/sales/job'
      fullPath: '/sales/job'
      preLoaderRoute: typeof LayoutSalesJobImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales_/supplier': {
      id: '/_layout/sales_/supplier'
      path: '/sales/supplier'
      fullPath: '/sales/supplier'
      preLoaderRoute: typeof LayoutSalesSupplierImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/technician_/item': {
      id: '/_layout/technician_/item'
      path: '/technician/item'
      fullPath: '/technician/item'
      preLoaderRoute: typeof LayoutTechnicianItemImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/technician_/job': {
      id: '/_layout/technician_/job'
      path: '/technician/job'
      fullPath: '/technician/job'
      preLoaderRoute: typeof LayoutTechnicianJobImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/technician_/request': {
      id: '/_layout/technician_/request'
      path: '/technician/request'
      fullPath: '/technician/request'
      preLoaderRoute: typeof LayoutTechnicianRequestImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales_/customer_/$customer_id': {
      id: '/_layout/sales_/customer_/$customer_id'
      path: '/sales/customer/$customer_id'
      fullPath: '/sales/customer/$customer_id'
      preLoaderRoute: typeof LayoutSalesCustomerCustomeridImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales_/customer_/create': {
      id: '/_layout/sales_/customer_/create'
      path: '/sales/customer/create'
      fullPath: '/sales/customer/create'
      preLoaderRoute: typeof LayoutSalesCustomerCreateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales_/job_/$job_id': {
      id: '/_layout/sales_/job_/$job_id'
      path: '/sales/job/$job_id'
      fullPath: '/sales/job/$job_id'
      preLoaderRoute: typeof LayoutSalesJobJobidImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales_/job_/create': {
      id: '/_layout/sales_/job_/create'
      path: '/sales/job/create'
      fullPath: '/sales/job/create'
      preLoaderRoute: typeof LayoutSalesJobCreateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales_/customer_/edit/$customer_id': {
      id: '/_layout/sales_/customer_/edit/$customer_id'
      path: '/sales/customer/edit/$customer_id'
      fullPath: '/sales/customer/edit/$customer_id'
      preLoaderRoute: typeof LayoutSalesCustomerEditCustomeridImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales_/job_/edit/$job_id': {
      id: '/_layout/sales_/job_/edit/$job_id'
      path: '/sales/job/edit/$job_id'
      fullPath: '/sales/job/edit/$job_id'
      preLoaderRoute: typeof LayoutSalesJobEditJobidImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBusinessRoute: typeof LayoutBusinessRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutInventoryRoute: typeof LayoutInventoryRoute
  LayoutSalesRoute: typeof LayoutSalesRoute
  LayoutTechnicianRoute: typeof LayoutTechnicianRoute
  LayoutAdminRoleRoute: typeof LayoutAdminRoleRoute
  LayoutAdminUserRoute: typeof LayoutAdminUserRoute
  LayoutBusinessJobRoute: typeof LayoutBusinessJobRoute
  LayoutBusinessScheduleRoute: typeof LayoutBusinessScheduleRoute
  LayoutInventoryItemRoute: typeof LayoutInventoryItemRoute
  LayoutInventoryLogRoute: typeof LayoutInventoryLogRoute
  LayoutInventoryRequestRoute: typeof LayoutInventoryRequestRoute
  LayoutSalesActivityRoute: typeof LayoutSalesActivityRoute
  LayoutSalesCustomerRoute: typeof LayoutSalesCustomerRoute
  LayoutSalesJobRoute: typeof LayoutSalesJobRoute
  LayoutSalesSupplierRoute: typeof LayoutSalesSupplierRoute
  LayoutTechnicianItemRoute: typeof LayoutTechnicianItemRoute
  LayoutTechnicianJobRoute: typeof LayoutTechnicianJobRoute
  LayoutTechnicianRequestRoute: typeof LayoutTechnicianRequestRoute
  LayoutSalesCustomerCustomeridRoute: typeof LayoutSalesCustomerCustomeridRoute
  LayoutSalesCustomerCreateRoute: typeof LayoutSalesCustomerCreateRoute
  LayoutSalesJobJobidRoute: typeof LayoutSalesJobJobidRoute
  LayoutSalesJobCreateRoute: typeof LayoutSalesJobCreateRoute
  LayoutSalesCustomerEditCustomeridRoute: typeof LayoutSalesCustomerEditCustomeridRoute
  LayoutSalesJobEditJobidRoute: typeof LayoutSalesJobEditJobidRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBusinessRoute: LayoutBusinessRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutInventoryRoute: LayoutInventoryRoute,
  LayoutSalesRoute: LayoutSalesRoute,
  LayoutTechnicianRoute: LayoutTechnicianRoute,
  LayoutAdminRoleRoute: LayoutAdminRoleRoute,
  LayoutAdminUserRoute: LayoutAdminUserRoute,
  LayoutBusinessJobRoute: LayoutBusinessJobRoute,
  LayoutBusinessScheduleRoute: LayoutBusinessScheduleRoute,
  LayoutInventoryItemRoute: LayoutInventoryItemRoute,
  LayoutInventoryLogRoute: LayoutInventoryLogRoute,
  LayoutInventoryRequestRoute: LayoutInventoryRequestRoute,
  LayoutSalesActivityRoute: LayoutSalesActivityRoute,
  LayoutSalesCustomerRoute: LayoutSalesCustomerRoute,
  LayoutSalesJobRoute: LayoutSalesJobRoute,
  LayoutSalesSupplierRoute: LayoutSalesSupplierRoute,
  LayoutTechnicianItemRoute: LayoutTechnicianItemRoute,
  LayoutTechnicianJobRoute: LayoutTechnicianJobRoute,
  LayoutTechnicianRequestRoute: LayoutTechnicianRequestRoute,
  LayoutSalesCustomerCustomeridRoute: LayoutSalesCustomerCustomeridRoute,
  LayoutSalesCustomerCreateRoute: LayoutSalesCustomerCreateRoute,
  LayoutSalesJobJobidRoute: LayoutSalesJobJobidRoute,
  LayoutSalesJobCreateRoute: LayoutSalesJobCreateRoute,
  LayoutSalesCustomerEditCustomeridRoute:
    LayoutSalesCustomerEditCustomeridRoute,
  LayoutSalesJobEditJobidRoute: LayoutSalesJobEditJobidRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/business': typeof LayoutBusinessRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/inventory': typeof LayoutInventoryRoute
  '/sales': typeof LayoutSalesRoute
  '/technician': typeof LayoutTechnicianRoute
  '/admin/role': typeof LayoutAdminRoleRoute
  '/admin/user': typeof LayoutAdminUserRoute
  '/business/job': typeof LayoutBusinessJobRoute
  '/business/schedule': typeof LayoutBusinessScheduleRoute
  '/inventory/item': typeof LayoutInventoryItemRoute
  '/inventory/log': typeof LayoutInventoryLogRoute
  '/inventory/request': typeof LayoutInventoryRequestRoute
  '/sales/activity': typeof LayoutSalesActivityRoute
  '/sales/customer': typeof LayoutSalesCustomerRoute
  '/sales/job': typeof LayoutSalesJobRoute
  '/sales/supplier': typeof LayoutSalesSupplierRoute
  '/technician/item': typeof LayoutTechnicianItemRoute
  '/technician/job': typeof LayoutTechnicianJobRoute
  '/technician/request': typeof LayoutTechnicianRequestRoute
  '/sales/customer/$customer_id': typeof LayoutSalesCustomerCustomeridRoute
  '/sales/customer/create': typeof LayoutSalesCustomerCreateRoute
  '/sales/job/$job_id': typeof LayoutSalesJobJobidRoute
  '/sales/job/create': typeof LayoutSalesJobCreateRoute
  '/sales/customer/edit/$customer_id': typeof LayoutSalesCustomerEditCustomeridRoute
  '/sales/job/edit/$job_id': typeof LayoutSalesJobEditJobidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/admin': typeof LayoutAdminRoute
  '/business': typeof LayoutBusinessRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/inventory': typeof LayoutInventoryRoute
  '/sales': typeof LayoutSalesRoute
  '/technician': typeof LayoutTechnicianRoute
  '/admin/role': typeof LayoutAdminRoleRoute
  '/admin/user': typeof LayoutAdminUserRoute
  '/business/job': typeof LayoutBusinessJobRoute
  '/business/schedule': typeof LayoutBusinessScheduleRoute
  '/inventory/item': typeof LayoutInventoryItemRoute
  '/inventory/log': typeof LayoutInventoryLogRoute
  '/inventory/request': typeof LayoutInventoryRequestRoute
  '/sales/activity': typeof LayoutSalesActivityRoute
  '/sales/customer': typeof LayoutSalesCustomerRoute
  '/sales/job': typeof LayoutSalesJobRoute
  '/sales/supplier': typeof LayoutSalesSupplierRoute
  '/technician/item': typeof LayoutTechnicianItemRoute
  '/technician/job': typeof LayoutTechnicianJobRoute
  '/technician/request': typeof LayoutTechnicianRequestRoute
  '/sales/customer/$customer_id': typeof LayoutSalesCustomerCustomeridRoute
  '/sales/customer/create': typeof LayoutSalesCustomerCreateRoute
  '/sales/job/$job_id': typeof LayoutSalesJobJobidRoute
  '/sales/job/create': typeof LayoutSalesJobCreateRoute
  '/sales/customer/edit/$customer_id': typeof LayoutSalesCustomerEditCustomeridRoute
  '/sales/job/edit/$job_id': typeof LayoutSalesJobEditJobidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/business': typeof LayoutBusinessRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/inventory': typeof LayoutInventoryRoute
  '/_layout/sales': typeof LayoutSalesRoute
  '/_layout/technician': typeof LayoutTechnicianRoute
  '/_layout/admin_/role': typeof LayoutAdminRoleRoute
  '/_layout/admin_/user': typeof LayoutAdminUserRoute
  '/_layout/business_/job': typeof LayoutBusinessJobRoute
  '/_layout/business_/schedule': typeof LayoutBusinessScheduleRoute
  '/_layout/inventory_/item': typeof LayoutInventoryItemRoute
  '/_layout/inventory_/log': typeof LayoutInventoryLogRoute
  '/_layout/inventory_/request': typeof LayoutInventoryRequestRoute
  '/_layout/sales_/activity': typeof LayoutSalesActivityRoute
  '/_layout/sales_/customer': typeof LayoutSalesCustomerRoute
  '/_layout/sales_/job': typeof LayoutSalesJobRoute
  '/_layout/sales_/supplier': typeof LayoutSalesSupplierRoute
  '/_layout/technician_/item': typeof LayoutTechnicianItemRoute
  '/_layout/technician_/job': typeof LayoutTechnicianJobRoute
  '/_layout/technician_/request': typeof LayoutTechnicianRequestRoute
  '/_layout/sales_/customer_/$customer_id': typeof LayoutSalesCustomerCustomeridRoute
  '/_layout/sales_/customer_/create': typeof LayoutSalesCustomerCreateRoute
  '/_layout/sales_/job_/$job_id': typeof LayoutSalesJobJobidRoute
  '/_layout/sales_/job_/create': typeof LayoutSalesJobCreateRoute
  '/_layout/sales_/customer_/edit/$customer_id': typeof LayoutSalesCustomerEditCustomeridRoute
  '/_layout/sales_/job_/edit/$job_id': typeof LayoutSalesJobEditJobidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/admin'
    | '/business'
    | '/dashboard'
    | '/inventory'
    | '/sales'
    | '/technician'
    | '/admin/role'
    | '/admin/user'
    | '/business/job'
    | '/business/schedule'
    | '/inventory/item'
    | '/inventory/log'
    | '/inventory/request'
    | '/sales/activity'
    | '/sales/customer'
    | '/sales/job'
    | '/sales/supplier'
    | '/technician/item'
    | '/technician/job'
    | '/technician/request'
    | '/sales/customer/$customer_id'
    | '/sales/customer/create'
    | '/sales/job/$job_id'
    | '/sales/job/create'
    | '/sales/customer/edit/$customer_id'
    | '/sales/job/edit/$job_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/admin'
    | '/business'
    | '/dashboard'
    | '/inventory'
    | '/sales'
    | '/technician'
    | '/admin/role'
    | '/admin/user'
    | '/business/job'
    | '/business/schedule'
    | '/inventory/item'
    | '/inventory/log'
    | '/inventory/request'
    | '/sales/activity'
    | '/sales/customer'
    | '/sales/job'
    | '/sales/supplier'
    | '/technician/item'
    | '/technician/job'
    | '/technician/request'
    | '/sales/customer/$customer_id'
    | '/sales/customer/create'
    | '/sales/job/$job_id'
    | '/sales/job/create'
    | '/sales/customer/edit/$customer_id'
    | '/sales/job/edit/$job_id'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/admin'
    | '/_layout/business'
    | '/_layout/dashboard'
    | '/_layout/inventory'
    | '/_layout/sales'
    | '/_layout/technician'
    | '/_layout/admin_/role'
    | '/_layout/admin_/user'
    | '/_layout/business_/job'
    | '/_layout/business_/schedule'
    | '/_layout/inventory_/item'
    | '/_layout/inventory_/log'
    | '/_layout/inventory_/request'
    | '/_layout/sales_/activity'
    | '/_layout/sales_/customer'
    | '/_layout/sales_/job'
    | '/_layout/sales_/supplier'
    | '/_layout/technician_/item'
    | '/_layout/technician_/job'
    | '/_layout/technician_/request'
    | '/_layout/sales_/customer_/$customer_id'
    | '/_layout/sales_/customer_/create'
    | '/_layout/sales_/job_/$job_id'
    | '/_layout/sales_/job_/create'
    | '/_layout/sales_/customer_/edit/$customer_id'
    | '/_layout/sales_/job_/edit/$job_id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/admin",
        "/_layout/business",
        "/_layout/dashboard",
        "/_layout/inventory",
        "/_layout/sales",
        "/_layout/technician",
        "/_layout/admin_/role",
        "/_layout/admin_/user",
        "/_layout/business_/job",
        "/_layout/business_/schedule",
        "/_layout/inventory_/item",
        "/_layout/inventory_/log",
        "/_layout/inventory_/request",
        "/_layout/sales_/activity",
        "/_layout/sales_/customer",
        "/_layout/sales_/job",
        "/_layout/sales_/supplier",
        "/_layout/technician_/item",
        "/_layout/technician_/job",
        "/_layout/technician_/request",
        "/_layout/sales_/customer_/$customer_id",
        "/_layout/sales_/customer_/create",
        "/_layout/sales_/job_/$job_id",
        "/_layout/sales_/job_/create",
        "/_layout/sales_/customer_/edit/$customer_id",
        "/_layout/sales_/job_/edit/$job_id"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/admin": {
      "filePath": "_layout.admin.tsx",
      "parent": "/_layout"
    },
    "/_layout/business": {
      "filePath": "_layout.business.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard": {
      "filePath": "_layout.dashboard.tsx",
      "parent": "/_layout"
    },
    "/_layout/inventory": {
      "filePath": "_layout.inventory.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales": {
      "filePath": "_layout.sales.tsx",
      "parent": "/_layout"
    },
    "/_layout/technician": {
      "filePath": "_layout.technician.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin_/role": {
      "filePath": "_layout.admin_.role.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin_/user": {
      "filePath": "_layout.admin_.user.tsx",
      "parent": "/_layout"
    },
    "/_layout/business_/job": {
      "filePath": "_layout.business_.job.tsx",
      "parent": "/_layout"
    },
    "/_layout/business_/schedule": {
      "filePath": "_layout.business_.schedule.tsx",
      "parent": "/_layout"
    },
    "/_layout/inventory_/item": {
      "filePath": "_layout.inventory_.item.tsx",
      "parent": "/_layout"
    },
    "/_layout/inventory_/log": {
      "filePath": "_layout.inventory_.log.tsx",
      "parent": "/_layout"
    },
    "/_layout/inventory_/request": {
      "filePath": "_layout.inventory_.request.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales_/activity": {
      "filePath": "_layout.sales_.activity.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales_/customer": {
      "filePath": "_layout.sales_.customer.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales_/job": {
      "filePath": "_layout.sales_.job.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales_/supplier": {
      "filePath": "_layout.sales_.supplier.tsx",
      "parent": "/_layout"
    },
    "/_layout/technician_/item": {
      "filePath": "_layout.technician_.item.tsx",
      "parent": "/_layout"
    },
    "/_layout/technician_/job": {
      "filePath": "_layout.technician_.job.tsx",
      "parent": "/_layout"
    },
    "/_layout/technician_/request": {
      "filePath": "_layout.technician_.request.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales_/customer_/$customer_id": {
      "filePath": "_layout.sales_.customer_.$customer_id.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales_/customer_/create": {
      "filePath": "_layout.sales_.customer_.create.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales_/job_/$job_id": {
      "filePath": "_layout.sales_.job_.$job_id.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales_/job_/create": {
      "filePath": "_layout.sales_.job_.create.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales_/customer_/edit/$customer_id": {
      "filePath": "_layout.sales_.customer_.edit.$customer_id.tsx",
      "parent": "/_layout"
    },
    "/_layout/sales_/job_/edit/$job_id": {
      "filePath": "_layout.sales_.job_.edit.$job_id.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
